{% set name = "code-aster" %}
{% set version = "17.2.9" %}
{% set sha256 = "d0e6e14a392214ec10a9e7a8832a487df0d85af86b69d88a01d4c51f1a18b9ff" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - fn: {{ name }}_{{ version }}.tar.gz
    url: https://gitlab.com/codeaster/src/-/archive/{{ version }}/src-{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      - patches/make_shared_use_env_FC_fallback.patch
  # Modified version of Metis changing integer sizes for indexes (IDXTYPEWIDTH 64) and including headers for direct linking to Aster
  # Modified version of Mumps changing integer, complex and real sizes to four bytes (fortran kind=4), waf configuration and metis renumbering
  - url: https://www.code-aster.org/FICHIERS/prerequisites/codeaster-prerequisites-20221225-oss.tar.gz
    sha256: 40243be37c647c6df05437d5baadd4522b9cab5de97a76e1d1fb79d1645dd5fc
    folder: codeaster-prerequisites/

build:
  number: 0
  skip: true  # [osx or win or (python_impl == 'pypy')]
  detect_binary_files_with_prefix: true
  rpaths:
    - lib/
    - lib/aster/
    - lib/petsc4py/lib      # [mpi != "nompi"]  
  run_exports:
    - {{ pin_subpackage('code-aster', max_pin='x.x') }}
requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - cmake
    - make  # [not win]
    - bison
    - flex
    - swig 4.2.1
  host:
    - python
    - numpy <2.0
    - scotch >=7
    - mfront 4.2
    - mgis 2.2
    - libboost-python-devel
    - setuptools
    - miss3d
    - libblas
    - liblapack
    - libxml2
    - openblas
    - zlib
    - patch
  run:
    - {{ pin_compatible('mgis', max_pin='x.x') }}
    - {{ pin_compatible('mfront', max_pin='x.x.x') }}
    - {{ pin_compatible('miss3d', max_pin='x.x') }}
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - libscotch
    - libboost-python-devel
    - libopenblas
    - libxml2
    - python
    - libxcrypt

test:
  imports:
    - asrun
    - code_aster
    - medcoupling
  requires:
    - {{ compiler('fortran') }}
  commands:
    - as_run --info
    - homard || true  # [unix]
    - as_run --test forma01a
    - as_run --test sslp114a
    - as_run --test mumps05a
    - as_run --test mumps01a
    - as_run --test umat001a
    - as_run --test zzzz121a
    #- as_run --test mfron01a
    - test -f $PREFIX/include/aster/aster.h

about:
  home: https://www.code-aster.org
  license: GPL-3.0-only AND CECILL-C AND Apache-2.0 AND LGPL-3.0-only
  license_family: GPL
  license_file:
    - dep-licenses/
  summary: 'Code_Aster : a finite element solver'
  description: |
    Code_Aster offers a full range of multiphysical analysis and modelling methods that go well beyond the standard functions of a thermomechanical calculation code: from seismic analysis to porous media via acoustics, fatigue, stochastic dynamics, etc..
  doc_url: https://www.code-aster.org/V2/doc/default/en/index.php?man=commande
  dev_url: https://sourceforge.net/projects/codeaster/

extra:
  recipe-maintainers:
    - Krande
    - ldallolio
