schema_version: 1

context:
  name: code-aster
  version: 17.3.7
  sha256: 5b07d9c6e41c4c1816a55240e1c0a6a47ac0332bb361a15ebcd1859aac03fb08

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://gitlab.com/codeaster/src/-/archive/${{ version }}/src-${{ version }}.tar.gz
    sha256: ${{ sha256 }}
    patches:
      - patches/make_shared_use_env_FC_fallback.patch
  # Modified version of Metis changing integer sizes for indexes (IDXTYPEWIDTH 64) and including headers for direct linking to Aster
  # Modified version of Mumps changing integer, complex and real sizes to four bytes (fortran kind=4), waf configuration and metis renumbering
  - url: https://www.code-aster.org/FICHIERS/prerequisites/codeaster-prerequisites-20221225-oss.tar.gz
    sha256: 40243be37c647c6df05437d5baadd4522b9cab5de97a76e1d1fb79d1645dd5fc
    target_directory: codeaster-prerequisites/

build:
  number: 1
  skip: osx or win or (python_impl == 'pypy') or match(python, ">=3.13")
  prefix_detection:
    ignore_binary_files: true
  dynamic_linking:
    rpaths:
      - lib/
      - lib/aster/
      - if: mpi != "nompi"
        then: lib/petsc4py/lib
    missing_dso_allowlist:
      - if: linux
        then: "*/libbibfor.so"
      - if: linux
        then: "*/libbibfor_ext.so"
      - if: linux
        then: "*/libbibc.so"
      - if: linux
        then: "*/libbibcxx.so"
      - if: linux
        then: "*/libAsterGC.so"
      - if: linux
        then: lib64/aster/libaster.so

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - if: linux
      then: libgomp
    - if: osx
      then: llvm-openmp
    - cmake <4
    - if: not win
      then: make
    - bison
    - flex
    - swig 4.2.1.*
    - hdf5 >=1.14
  host:
    - python
    - numpy <2.0
    - scotch >=7
    - mfront
    - mgis
    - libboost-python-devel
    - setuptools
    - miss3d
    - libblas
    - liblapack
    - libxml2
    - openblas
    - zlib
    - patch
    - diffutils
    - medcoupling
    - hdf5 >=1.14
    - scipy
  run:
    - ${{ pin_compatible('mgis', upper_bound='x.x') }}
    - ${{ pin_compatible('mfront', upper_bound='x.x.x') }}
    - ${{ pin_compatible('miss3d', upper_bound='x.x') }}
    - ${{ pin_compatible('medcoupling', upper_bound='x.x') }}
    - ${{ pin_compatible('libmed', upper_bound='x.x') }}
    - ${{ pin_compatible('numpy', upper_bound='x.x') }}
    - libscotch
    - libboost-python-devel
    - libopenblas
    - libxml2
    - python
    - libxcrypt
    - scipy
  run_exports:
    - ${{ pin_subpackage('code-aster', upper_bound='x.x') }}

tests:
  - python:
      imports:
        - asrun
        - code_aster
        - medcoupling
  - requirements:
      run:
        - ${{ compiler('fortran') }}
    script:
      - as_run --info
      - if: unix
        then: homard || true
      - as_run --test forma01a
      - as_run --test sslp114a
      - as_run --test mumps05a
      - as_run --test mumps01a
      - as_run --test umat001a
      - as_run --test zzzz121a
      - test -f $PREFIX/include/aster/aster.h

about:
  license: GPL-3.0-only AND CECILL-C AND Apache-2.0 AND LGPL-3.0-only
  license_file:
    - dep-licenses/
  summary: "Code_Aster : a finite element solver"
  description: |
    Code_Aster offers a full range of multiphysical analysis and modelling methods that go well beyond the standard functions of a thermomechanical calculation code: from seismic analysis to porous media via acoustics, fatigue, stochastic dynamics, etc..
  homepage: https://www.code-aster.org
  repository: https://gitlab.com/codeaster/
  documentation: https://www.code-aster.org/V2/doc/default/en/index.php?man=commande

extra:
  recipe-maintainers:
    - Krande
    - ldallolio
