schema_version: 1

context:
  name: code-aster
  version: 17.3.15
  sha256: 99e6b6b9d6f463ad0205f458e0be6e0ce2e73cb5508a1faf273232dc49213f40
  build_base: 0
  mpi_num: ${{ 100 if mpi == 'nompi' else 0 }}
  build: ${{ build_base|int + mpi_num|int }}
  mpi_prefix: ${{ mpi or 'nompi' }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://gitlab.com/codeaster/src/-/archive/${{ version }}/src-${{ version }}.tar.gz
    sha256: ${{ sha256 }}
    patches:
      - patches/make_shared_use_env_FC_fallback.patch
      - patches/install_dir_override.patch
  # Modified version of Metis changing integer sizes for indexes (IDXTYPEWIDTH 64) and including headers for direct linking to Aster
  # Modified version of Mumps changing integer, complex and real sizes to four bytes (fortran kind=4), waf configuration and metis renumbering

build:
  number: 1
  skip: osx or win or (python_impl == 'pypy') or match(python, ">=3.13")
  string: py${{ python | replace('.', '') }}_${{ mpi_prefix }}_h${{ hash }}_${{ build }}
  prefix_detection:
    ignore_binary_files: true
  dynamic_linking:
    rpaths:
      - lib/
      - lib/aster/
      - if: mpi != "nompi"
        then: lib/petsc4py/lib
    missing_dso_allowlist:
      - if: linux
        then:
          - "*/libbibfor.so"
          - "*/libbibfor_ext.so"
          - "*/libbibc.so"
          - "*/libbibcxx.so"
          - "*/libAsterGC.so"
          - lib64/aster/libaster.sozzz

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - if: linux
      then: libgomp
    - if: osx
      then: llvm-openmp
    - cmake <4
    - if: not win
      then: make
    - bison
    - flex
    - swig 4.2.1.*
    - hdf5 >=1.14
    - waf ==2.1.5
  host:
    - python
    - numpy <2.0
    - libboost-python-devel
    - setuptools
    - libblas
    - liblapack
    - libxml2
    - openblas
    - zlib
    - patch
    - diffutils
    - scotch >=7
    - mfront
    - mgis
    - miss3d
    - metis
    - medcoupling
    - if: (mpi == 'nompi') and not win
      then:
        - mumps-seq
    - if: (mpi != 'nompi') and not win
      then:
        - ${{ mpi }}
        - scalapack >=2.2.0,<3
        - mumps-mpi
        - parmetis
        - petsc
        - slepc
        - mpi4py
        - petsc4py
        - slepc4py
    - mumps-include
    - hdf5 >=1.14
    - scipy
  run:
    - ${{ pin_compatible('mgis', upper_bound='x.x') }}
    - ${{ pin_compatible('mfront', upper_bound='x.x.x') }}
    - ${{ pin_compatible('miss3d', upper_bound='x.x') }}
    - ${{ pin_compatible('medcoupling', upper_bound='x.x') }}
    - ${{ pin_compatible('libmed', upper_bound='x.x') }}
    - ${{ pin_compatible('numpy', upper_bound='x.x') }}
    - libscotch
    - libboost-python-devel
    - libopenblas
    - libxml2
    - python
    - libxcrypt
    - scipy
  run_exports:
    - ${{ pin_subpackage('code-aster', upper_bound='x.x') }}

tests:
  - python:
      imports:
        - asrun
        - code_aster
        - medcoupling
  - requirements:
      run:
        - ${{ compiler('fortran') }}
    script:
      - as_run --info
      - if: unix
        then: homard || true
      - as_run --test forma01a
      - as_run --test sslp114a
      - as_run --test mumps05a
      - as_run --test mumps01a
      - as_run --test umat001a
      - as_run --test zzzz121a
      - test -f $PREFIX/include/aster/aster.h

about:
  license: GPL-3.0-only AND CECILL-C AND Apache-2.0 AND LGPL-3.0-only
  license_file:
    - dep-licenses/
  summary: "Code_Aster : a finite element solver"
  description: |
    Code_Aster offers a full range of multiphysical analysis and modelling methods that go well beyond the standard functions of a thermomechanical calculation code: from seismic analysis to porous media via acoustics, fatigue, stochastic dynamics, etc..
  homepage: https://www.code-aster.org
  repository: https://gitlab.com/codeaster/
  documentation: https://www.code-aster.org/V2/doc/default/en/index.php?man=commande

extra:
  recipe-maintainers:
    - Krande
    - ldallolio
